name: alruba_waterapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  supabase_flutter: ^2.8.4
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  intl: ^0.18.0
  uuid: ^4.5.1
  collection: ^1.18.0
  syncfusion_flutter_charts: ^29.1.38
  syncfusion_flutter_core: ^29.1.38
  fl_chart: ^0.71.0
  flutter_multi_formatter: ^2.13.7
  shimmer: ^3.0.0
  excel: ^2.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  device_info_plus: ^11.5.0
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  hive_generator: ^1.1.3

  # Launcher-icon generator
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "assets/LOGO.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/LOGO.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/LOGO.png
    - .env
